--- 
workload:
  - type: Native 
    path: combined_workload.json
    options:
      profile_path: combined_profiles.json
      

hosts: 
  - count: 100
    cpus: 30
    cpu_speed: 1
    memory: 120
    name_prefix: m
  - count: 100
    cpus: 60
    cpu_speed: 1
    memory: 60
    name_prefix: c

